[package]
name = "discord-bot"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
dotenvy = "0.15.7"
poise = "0.6.1"
tokio = { version = "1.39.2", features = ["rt-multi-thread", "macros"] }
